### ISSUE TITLE
Add filter hook to services

### ISSUE THREAD

**Issue by gaambo** [ndiego/social-sharing-block#17]
Hi, first of all: Thanks for this great and simple block!

Currently I'm adding a custom block variation to add a "Copy Link" block (similar to #6). But for replacing the url, label and icon I need to use some nasty regex. Well actually, for url and label I can use the new WP_HTML_Tag_Processor, but for replacing the SVG icon in the `render_block_outermost/social-sharing-link` I need regex. 

Would you accept a PR that adds a simple filter hook at the end of `get_link_services`, which could be used to add custom services or replace an icon. Of course, extenders would still need to register their variations in the editor. 

Since I've already got it running, I could also provide a PR for #6, allthough that needs frontend JS and I'm not sure if you want to include that in your plugin.

**Comment by ndiego** [comment]
Hey @gaambo thanks for the issue. 

> allthough that needs frontend JS and I'm not sure if you want to include that in your plugin.

Yeah, I have tinkered with this a bit, but want to avoid frontend JS for right now. 

> Would you accept a PR that adds a simple filter hook at the end of get_link_services

I went ahead and added this [here](https://github.com/ndiego/social-sharing-block/blob/0a10049e7774bdcfe8ed357a4b663d747cf06b2f/src/social-sharing-link/utils.php#L205). I am shipping v0.8.0 later today, which will include the filter.

**Comment by philcable** [comment]
@ndiego Thanks a ton for adding the `social_sharing_block_services_data` filter!

What would you think about adding a filter on the [variations](https://github.com/ndiego/social-sharing-block/blob/main/src/social-sharing-link/variations.js#L28) list? I know that might seem silly at first blush because we can just use the `registerBlockVariation` function, but since the functions in [social-list.js](https://github.com/ndiego/social-sharing-block/blob/main/src/social-sharing-link/social-list.js) loop through that variations array, variations registered through `registerBlockVariation` end up falling back to the "Email" service when displayed in the editor. Or, maybe there's a more clever way to address that which I'm overlooking.

Thanks again for the great plugin!

**Comment by gaambo** [comment]
> What would you think about adding a filter on the [variations](https://github.com/ndiego/social-sharing-block/blob/main/src/social-sharing-link/variations.js#L28) list? I know that might seem silly at first blush because we can just use the `registerBlockVariation` function, but since the functions in [social-list.js](https://github.com/ndiego/social-sharing-block/blob/main/src/social-sharing-link/social-list.js) loop through that variations array, variations registered through `registerBlockVariation` end up falling back to the "Email" service when displayed in the editor. Or, maybe there's a more clever way to address that which I'm overlooking.
> 
> Thanks again for the great plugin!

You should be able to define an icon and title when registering your variation. Or what exactly do you mean by „when displayed in the editor“?

**Comment by philcable** [comment]
Hi @gaambo! Sorry for the delayed response, the notification of your comment somehow slipped through the cracks. Here's a screenshot of what I'm seeing:

<img width="609" alt="custom-block" src="https://github.com/ndiego/social-sharing-block/assets/6403569/3d11cec3-7e4f-4fab-9725-ac8571705fe5">

&nbsp;
The icon and title of my variation are displaying correctly in the sidebar, but the Mail icon is displaying in the content area. This is due to the logic at https://github.com/ndiego/social-sharing-block/blob/main/src/social-sharing-link/social-list.js#L31 and https://github.com/ndiego/social-sharing-block/blob/main/src/social-sharing-link/social-list.js#L50, which falls back to the Mail block settings when the variation isn't found in the array provided in the [variations](https://github.com/ndiego/social-sharing-block/blob/main/src/social-sharing-link/variations.js) file.

**Comment by gaambo** [comment]
@philcable Oh sorry, I was talking about the block icon 🙈 
In this case: You are right, a client-side filter in the editor would be great to change the icon + label displayed while editing.
